### PR TITLE
Bug wave2 727 back end functionality to cta added to text brick

### PR DESCRIPTION
**Pull request by mhughes2012**

### CODE REVIEW

**Comment by dpfitzsi** [comment]
Hi Michael... this one is in conflict. Can you get these resolved?

**Comment by mhughes2012** [comment]
@dpfitzsi merged and pushed to 727 branch

**Comment by dpfitzsi** [comment]
AH! More conflicts. Can you resolve these and I'll merge.

**Comment by mhughes2012** [comment]
merged.

**Comment by dpfitzsi** [comment]
Hi Michael. I had merged this in and when I pulled it down I'm getting a bunch of merged files related to Drupal core and contrib modules. So I'm reverting this to avoid conflicts. Can you readd your files into a new pull request and then I can merge those in.

**Pull request merged**
