### PR TITLE
Subtask wave2 798 image + text reqd fields char counts new fields

### PR DESCRIPTION
**Pull request by mhughes2012**

### CODE REVIEW

**Comment by mhughes2012** [comment]
i've updated the css for seven theme to be hooked to use our own css

**Comment by dpfitzsi** [comment]
Conflicts on this branch.

**Comment by mhughes2012** [comment]
Hi @dpfitzsi, this has now been resolved.

**Comment by dpfitzsi** [comment]
Merged in 417

**Pull request closed without merging**
