### PR TITLE
Wave2 650 content ownership code cleanup

### PR DESCRIPTION
**Pull request by balrajb**

### CODE REVIEW

**Comment by dpfitzsi** [comment]
Balraj, it appears that this is in conflict. Can you update it ASAP so we can merge to develop?

**Comment by balrajb** [comment]
Conflict resolved. Because this is a quite a big re-structure, I would recommend to test entire content ownership flow.

**Comment by balrajb** [comment]
@nindusaini found few issues in bulk update. Changes committed accordingly

**Comment by dpfitzsi** [comment]
Hi Balraj, looks like we have a conflict with this one now. I will get it merged once it's resolved so we can move forward on this.

**Comment by balrajb** [comment]
conflicts resolved!

**Pull request merged**
