### PR TITLE
WAVE2-960-adding new specialization field with a link

### PR DESCRIPTION
**Pull request by nindusaini**

### CODE REVIEW

**Comment by mhughes2012** [comment]
(reviewing instead of Robb)
Looks good and thorough. 
There are conflicts though.

**Comment by dpfitzsi** [comment]
Just changing reviewers since Mike did this one. Mike can you set your review as approved?

**Comment by dpfitzsi** [comment]
Conflicts Navinder... can you resolve so that we can merge?

**Comment by nindusaini** [comment]
Conflicts resolved

**Pull request merged**
