### PR TITLE
Bug wave2 711 field standardization fielded panes misc bricks

### PR DESCRIPTION
**Pull request by mhughes2012**

### CODE REVIEW

**Comment by dpfitzsi** [comment]
Hi Michael... this one is in conflict. Can you get these resolved?

**Comment by dpfitzsi** [comment]
Hi Michael... this one is in conflict. Can you get these resolved?

**Comment by mhughes2012** [comment]
@dpfitzsi fixed the conflicts and pushed them to the 711 branch

**Comment by dpfitzsi** [comment]
Ugh it happened again... can you resolve these conflicts?

**Comment by mhughes2012** [comment]
Merged!

**Pull request merged**
