### PR TITLE
Bug wave2 439 mini cta buttons

### PR DESCRIPTION
**Pull request by TDRoden**
Fixing a number of Mini CTA layout bugs.

### CODE REVIEW

**Comment by dpfitzsi** [comment]
Hi Terry, there are some conflicts. Can you rebuild your commit and then I'll get this merged.

**Comment by TDRoden** [comment]
Should be good to go now Dan - looks like it was complaining about the work I did for Wave2-414.

**Comment by dpfitzsi** [comment]
Hi Terry, did this commit also include the work you did on 444?

**Comment by TDRoden** [comment]
Yup - it was all so intertwined it was hard to split up per Jira ticket.

**Comment by dpfitzsi** [comment]
Thanks for the update. I have added your note to the Jira ticket.

**Pull request merged**
