### PR TITLE
WAVE2-1027-took  out per field access, checking access for the page instead

### PR DESCRIPTION
**Pull request by nindusaini**

### CODE REVIEW

**Comment by mhughes2012** [comment]
Resolved the conflict. 

The Content ownership functionality was originally going to be customized as a special case in the VTF, but as of this jira ticket [wave2-1027] the ownership group is just for show until a different decision is made.

**Comment by balrajb** [comment]
thanks @mhughes2012 for removing content ownership code, there is another conflict now.

**Comment by mhughes2012** [comment]
conflicts resolved.

**Comment by balrajb** [comment]
thanks @mhughes2012 for resolving conflicts.

**Pull request merged**
